---
version: '3'
services:
  jupyter:
    image: quay.io/jupyter/datascience-notebook
    restart: unless-stopped
    container_name: jupyter
    volumes:
      - "MEGA:/home/jovyan/MEGA"
    ports:
      - "127.0.0.1:8888:8888"
    command: start.sh jupyter lab --ServerApp.token=''
  rstudio:
    image: docker.io/rocker/verse
    restart: unless-stopped
    container_name: rstudio
    volumes:
      - "MEGA:/home/rstudio/MEGA"
    ports:
      - "127.0.0.1:8787:8787"
    environment:
      - DISABLE_AUTH=true
  shiny:
    image: docker.io/rocker/shiny-verse
    restart: unless-stopped
    container_name: shiny
    ports:
      - "127.0.0.1:3838:3838"
