---
version: '3'
services:
  jupyter:
    image: quay.io/jupyter/datascience-notebook
    restart: unless-stopped
    container_name: jupyter
    volumes:
      - "~/MEGA/Rcode:/home/jovyan/Rcode"
      - "~/MEGA/PythonCode:/home/jovyan/PythonCode"
    ports:
      - "127.0.0.1:8888:8888"
    command: start.sh jupyter lab --ServerApp.token=''
